INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ Jaén nº 24', 'Parroquia San Pedro', 'Don Jose Luis', '678 489 282', NEXTVAL('hibernate_sequence'));
INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ Rosario nº 78', 'Comedor social San Juan de Dios', 'Francisco Gomez', '956 783 211', NEXTVAL('hibernate_sequence'));
INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ Betis nº 196', 'Caritas', 'Sara Fernández', '656 467 629', NEXTVAL('hibernate_sequence'));
INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ López de gomara nº 56, bloque 2, 4ºA', 'Banco de alimentos', 'Mario Marquez', '756 472 987', NEXTVAL('hibernate_sequence'));
INSERT INTO destinatario(direccion, nombre, persona_contacto, telefono, id) VALUES ('C/ Esperanza de triana nº 34', 'Plataforma del voluntariado social', 'Ignacio Franco', '676 439 675', NEXTVAL('hibernate_sequence'));
INSERT INTO clase(nombre, tutor, id) VALUES ('2 DAM' ,'Luis Miguel López' ,NEXTVAL('hibernate_sequence'));
INSERT INTO clase(nombre, tutor, id) VALUES ('1 DAM' ,'Miguel Campos' ,NEXTVAL('hibernate_sequence'));
INSERT INTO clase(nombre, tutor, id) VALUES ('1 FPB' ,'Julio Vera' ,NEXTVAL('hibernate_sequence'));
INSERT INTO clase(nombre, tutor, id) VALUES ('1 COMERCIO' ,'Mónica Naranjo' ,NEXTVAL('hibernate_sequence'));
INSERT INTO clase(nombre, tutor, id) VALUES ('2 AYF' ,'Paco Pepe' ,NEXTVAL('hibernate_sequence'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Pasta', NEXTVAL('hibernate_sequence'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Dulces', NEXTVAL('hibernate_sequence'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Legumbres', NEXTVAL('hibernate_sequence'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Arroz', NEXTVAL('hibernate_sequence'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Leche', NEXTVAL('hibernate_sequence'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Huevos', NEXTVAL('hibernate_sequence'));
INSERT INTO tipo_alimento(nombre, id) VALUES ('Carne', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (6, '2022-12-13', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (6, '2022-12-16', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (7, '2022-12-17', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (7, '2022-12-12', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (7, '2022-12-17', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (8, '2022-12-18', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (9, '2022-12-19', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (9, '2022-12-21', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (9, '2022-12-23', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (9, '2022-12-20', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (10, '2022-12-18', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (7, '2022-12-16', NEXTVAL('hibernate_sequence'));
INSERT INTO  aportacion (clase_id, fecha, id) VALUES (10, '2022-12-16', NEXTVAL('hibernate_sequence'));
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8, 11, 18, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (5.7, 16, 18, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (4, 14, 18, 3);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (10, 12, 19, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8.2, 11, 20, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (4.6, 12, 20, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7, 17, 21, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (5.8, 17, 21, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.2, 11, 21, 3);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (6, 12, 22, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (14, 13, 22, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (12.5, 13, 22, 3);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (9, 15, 22, 4);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (10.3, 12, 23, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (12, 11, 24, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (17.2, 14, 25, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (9, 16, 25, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8, 12, 25, 3);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.6, 11, 26, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (8.7, 13, 27, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (2.8, 17, 27, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (11, 15, 28, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (6.4, 15, 29, 1);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (16, 14, 29, 2);
INSERT INTO detalle_aportacion (cantidad_kg, tipo_alimento, aportacion_id, linea_id) VALUES (7.9, 16, 30, 1);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 11), 11);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 12), 12);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 13), 13);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 14), 14);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 15), 15);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 16), 16);
INSERT INTO  kilos_disponibles(cantidad_disponible, tipo_alimento) VALUES ((SELECT SUM(cantidad_kg) FROM detalle_aportacion WHERE tipo_alimento = 17), 17);
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (1, 0, 1, NEXTVAL('hibernate_sequence'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (2, 0, 2, NEXTVAL('hibernate_sequence'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (3, 0, 3, NEXTVAL('hibernate_sequence'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (4, 0, 4, NEXTVAL('hibernate_sequence'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (1, 0, 5, NEXTVAL('hibernate_sequence'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (1, 0, 6, NEXTVAL('hibernate_sequence'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (3, 0, 7, NEXTVAL('hibernate_sequence'));
INSERT INTO caja(destinatario, kilos_totales, num_caja, id) VALUES (4, 0, 8, NEXTVAL('hibernate_sequence'));
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (6, 31, 11);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (8, 31, 12);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (12, 32, 11);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (20, 33, 13);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (8, 34, 11);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (11, 35, 15);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (15, 36, 13);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (16, 37, 14);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (7, 34, 14);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (10, 38, 17);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (7, 34, 16);
INSERT INTO tiene(cantidad_kgs, caja_id, tipo_alimento_id) VALUES (5, 38, 12);
UPDATE caja c SET kilos_totales = (SELECT SUM(cantidad_kgs) FROM tiene t WHERE t.caja_id = c.id);
UPDATE kilos_disponibles k SET cantidad_disponible = cantidad_disponible - (SELECT SUM(cantidad_kgs) FROM tiene t WHERE t.tipo_alimento_id = k.tipo_alimento);
UPDATE caja c SET qr = CONCAT('http://localhost:8080/caja/', c.id);